 templates_path = ['_templates']
 
 # The suffix of source filenames.
source_suffix = '.rst'
 
 # The encoding of source files.
 # source_encoding = 'utf-8-sig'
 
 # General information about the project.
 project = u'python_template'
copyright = u'2017-2019, reactive-firewall'
 
 # The version info for the project you're documenting, acts as replacement for
 # |version| and |release|, also used in various other places throughout the
 # The short X.Y version.
 version = 'v1.1'
 # The full version, including alpha/beta/rc tags.
release = 'v1.1.1'
 
 # The language for content autogenerated by Sphinx. Refer to documentation
 # for a list of supported languages.